### mattermost-k8s/k8s/db/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: mattermost-db
  namespace: mattermost
  labels:
    app: mattermost
    tier: db
spec:
  ports:
  - port: 5432
    targetPort: 5432
    protocol: TCP
  selector:
    app: mattermost-db
