### mattermost-k8s/k8s/db/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: mattermost-db
  namespace: mattermost
  labels:
    app: mattermost
    tier: db # サービスがデータベースの役割を持つことを示すラベル
spec:
  ports:
  - port: 5432           # クラスター内の他のリソースが接続に使用するポート
    targetPort: 5432     # バックエンドPodがリッスンするポート
    protocol: TCP        # データベース接続に使用するプロトコル
  selector:
    app: mattermost-db   # このラベルを持つPodにトラフィックをルーティング
