### mattermost-k8s/k8s/cert-manager/letsencrypt-issuer.yaml
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory # Let's EncryptのACME APIエンドポイント
    email: karbii774@gmail.com
    privateKeySecretRef:
      name: letsencrypt-prod # ACMEチャレンジの秘密鍵を保存するSecretの名前
    solvers:
    - http01:
        ingress:
          class: nginx # Nginx Ingress Controllerを使用してHTTP-01チャレンジを処理
